Repository defactor-com/ui-kit, pull requests merged in 2024-03, with the labels that each got.

#78 feat(table): add filters
  package.json
  public/assets/approve-icon.svg
  public/assets/filter-options-icon.svg
  src/components/DropDown/index.tsx
  src/components/Table/index.tsx
  src/index.ts
  src/scss/components/DropDown/_dropdown.scss
  src/scss/components/Table/_table.scss
  src/scss/styles.scss
  src/stories/DropDown.stories.tsx
  src/stories/Table.stories.tsx
  yarn.lock
Labels: enhancement, WIP, ui-kit

#82 Feat/test in table component 81
  package.json
  src/components/DropDown/index.tsx
  src/components/Table/index.tsx
  src/scss/components/DropDown/_dropdown.scss
  src/scss/components/Table/_table.scss
  src/stories/Table.stories.tsx
  yarn.lock
Labels: UI / UX Design, Frontend, ui-kit

#83 Feat/add pie and bar charts 73 74
  package.json
  src/components/BarChart/index.tsx
  src/components/ChartContainer/index.tsx
  src/components/Dashboard/index.tsx
  src/components/Graphic/index.tsx
  src/components/Graphic/useGraphicState.tsx
  src/components/PieChart/index.tsx
  src/index.ts
  src/scss/components/BarChart/_barChart.scss
  src/scss/components/Dashboard/_dashboard.scss
  src/scss/components/PieChart/_pieChart.scss
  src/scss/styles.scss
  src/stories/BarChart.stories.tsx
  src/stories/Dashboard.stories.tsx
  src/stories/Graphic.stories.tsx
  src/stories/PieChart.stories.tsx
Labels: WIP

#84 Fix/lendborrow component does not accept formatted inputs 80
  package.json
  src/components/Input/index.tsx
  src/components/LendBorrow/index.tsx
  src/stories/LendBorrow.stories.tsx
Labels: bug, enhancement, Frontend

#93 fix(table): update filters selected by onchange
  .changeset/friendly-crews-invent.md
  public/assets/approve-icon.svg
  src/components/DropDown/index.tsx
  src/components/Table/index.tsx
Labels: bug, enhancement, UI / UX Design

#97 fix(lendBorrow): state NaN remove
  .changeset/wise-spoons-sleep.md
  src/components/Input/index.tsx
  src/components/Table/index.tsx
Labels: bug
